input_number: !include vars/input_number.yaml
input_text: !include vars/input_text.yaml
input_datetime: !include vars/input_datetime.yaml
input_boolean: !include vars/input_boolean.yaml
var: !include vars/variables.yaml
template:
  - sensor: !include_dir_merge_list templates
automation: !include_dir_merge_list automations

