  t0:
    name: T0
    min: -100000
    max: 100000
    step: 0.1
    mode: box

  t1:
    name: T1
    min: -100000
    max: 100000
    step: 0.1
    mode: box

  diff:
    name: Difference
    min: -1000
    max: 1000
    step: 0.1
    mode: box

  trip1_v0:
    name: Start
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box

  trip1_v1:
    name: End
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box

  trip1_fuel_diff:
    name: Trip 1 Fuel
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box




  trip2_v0:
    name: Start
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box

  trip2_v1:
    name: End
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box

  trip2_fuel_diff:
    name: Trip 2 Fuel
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box


### fuel rework:
  t1v0:
    name: Start
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box

  t1v1:
    name: End
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box

  t1fd:
    name: Trip 1 Fuel
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box




  t2v0:
    name: Start
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box

  t2v1:
    name: End
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box

  t2fd:
    name: Trip 2 Fuel
    min: -2147483648
    max: 2147483647
    step: 0.1
    mode: box

