appdaemon:
  latitude: 0
  longitude: 0
  elevation: 30
  time_zone: Europe/Berlin
  plugins:
    HASS:
      type: hass
      ha_url: "http://127.0.0.1:8123"
      token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2ODYxZWI0NWJiZWU0NDYzODIwMjFkMzFmYTQ5N2E2NyIsImlhdCI6MTcwOTM5OTk1NiwiZXhwIjoyMDI0NzU5OTU2fQ.FDn0whzj9jlv3GeUVlSpxSndfgABVEGp_fMITs1VZf8"
      cert_verify: True
    MQTT: 
      type: mqtt 
      namespace: mqtt
      client_user: "monitor"
      client_password: "Moenmarin123"
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
